################################
### Services & Ingresses
################################

kind: Service
apiVersion: v1
metadata:
  name: handuan-x-pylibrary
  namespace: base
  labels:
    app.kubernetes.io/name: handuan-x-pylibrary
    app.kubernetes.io/version: "v1.0.0"
spec:
  ports:
    - name: api
      port: 9100
  selector:
    app.kubernetes.io/name: handuan-x-pylibrary

---


################################
### Deployments
################################

kind: Deployment
apiVersion: apps/v1
metadata:
  name: handuan-x-pylibrary
  namespace: base
  labels:
    app.kubernetes.io/name: handuan-x-pylibrary
    app.kubernetes.io/version: "v1.0.0"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: handuan-x-pylibrary
  template:
    metadata:
      labels:
        app.kubernetes.io/name: handuan-x-pylibrary
        app.kubernetes.io/version: "v1.0.0"
    spec:
      containers:
        - name: handuan-x-pylibrary
          image: swr.cn-north-4.myhuaweicloud.com/handuan/x-pylibrary:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9100
              name: api
              protocol: TCP
          volumeMounts:
            # Create on-disk volume to store exec logs
            - mountPath: /data
              name: data-volume
      volumes:
        - name: data-volume
          emptyDir: {}